"""add_is_admin_to_patient

Revision ID: 0de57ffb15c1
Revises: 158bd9315598
Create Date: 2026-06-10 18:48:03.432136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0de57ffb15c1'
down_revision: Union[str, None] = '158bd9315598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'is_admin')
    # ### end Alembic commands ###
