"""add clinical_summary and no_show_risk to appointment

Revision ID: 4fb8fed74771
Revises: d1a5c8e3f9b2
Create Date: 2026-06-16 18:51:56.154435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fb8fed74771'
down_revision: Union[str, None] = 'd1a5c8e3f9b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('clinical_summary', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('no_show_probability', sa.Float(), nullable=True))
    op.add_column('appointments', sa.Column('no_show_risk_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'no_show_risk_reason')
    op.drop_column('appointments', 'no_show_probability')
    op.drop_column('appointments', 'clinical_summary')
    # ### end Alembic commands ###
